name: build

on:
  workflow_call:
    inputs:
      aws_role_to_assume_arn:
        required: true
        type: string

      network_name:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string

      gh_repo_ref:
        required: true
        type:     string
      
      prevent_github_organization:
        type:    string
        default: "true"
      github_organization:
        type:    string
        default: "pharmaledgerassoc"

    secrets:
      gh_token:
        required: true

env:
  NODE_VERSION:      "20"

  GH_TOKEN:     ${{ secrets.gh_token }}
  
  GH_REPO_NAME: "pharmaledgerassoc/LWA"
  GH_REPO_REF:  ${{ inputs.gh_repo_ref }}

  AWS_IAM_ROLE_ARN_TO_ASSUME: ${{ inputs.aws_role_to_assume_arn }}

  NETWORK_NAME: ${{ inputs.network_name }}
  FQDN:         ${{ inputs.fqdn }}

  PREVENT_GITHUB_ORGANIZATION: ${{ inputs.prevent_github_organization }}
  GITHUB_ORGANIZATION:         ${{ inputs.github_organization }}
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  npm:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          token:      ${{ env.GH_TOKEN }}
          repository: ${{ env.GH_REPO_NAME }}
          ref:        ${{ env.GH_REPO_REF }}
          path:       "./LWA"
          
      - name: install
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: |
          export PREVENT_GITHUB_ORGANIZATION=${{ env.PREVENT_GITHUB_ORGANIZATION }}
          export GITHUB_ORGANIZATION=${{ env.GITHUB_ORGANIZATION }}
          
          cd ./LWA/code

          npm install

          rm -rf lib/zxing-wrapper/package.json node_modules

          mv app ${{ env.GH_REPO_REF }}

          zip -r build.zip *

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name:           build.zip
          path:           ./LWA/code/build.zip
          retention-days: 1
