name: build

on:
  workflow_call: 
    inputs:
      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string

    secrets:
      gh_token:
        required: true
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  npm:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.GH_TOKEN }}
          repository: ${{ env.TF_VAR_gh_repo_name }}
          ref:        ${{ env.TF_VAR_gh_repo_ref }}
          path:       "./LWA"
          
      - name: install
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: build
        run: |
          export PREVENT_GITHUB_ORGANIZATION=${{ env.PREVENT_GITHUB_ORGANIZATION }}
          export GITHUB_ORGANIZATION=${{ env.GITHUB_ORGANIZATION }}
          
          cd ./LWA/code

          npm install

          rm -rf lib/zxing-wrapper/package.json node_modules

          mv app ${{ env.TF_VAR_app_build_version }}

          zip -r build.zip *

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name:           build.zip
          path:           ./LWA/code/build.zip
          retention-days: 1
