name: deploy

on:
  workflow_call:
    inputs:
      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

           echo "TF_VAR_network=${{ inputs.network }}" >> $GITHUB_ENV
           echo "TF_VAR_fqdn=${{ inputs.fqdn }}" >> $GITHUB_ENV

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_BUILD_IAM_ROLE_TO_ASSUME_ARN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.gh_token }}
          repository: ${{ env.TF_VAR_gh_repo_name }}
          ref:        ${{ env.TF_VAR_gh_repo_ref }}
          path:       "./LWA"

      - name: download build
        run: |
          aws s3 cp --quiet s3://${{ env.AWS_BUILD_S3_BUCKET_NAME }}/${{ env.TF_VAR_app_build_version }}/lwa-build-${{ env.TF_VAR_app_build_version }}.zip lwa-build-${{ env.TF_VAR_app_build_version }}.zip

      - name: unzip build
        run: |
          ls -la

          mkdir ./LWA/terraform/build

          unzip -q lwa-build-${{ env.TF_VAR_app_build_version }}.zip -d ./LWA/terraform/build

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: |
          cd ./LWA/terraform

          /bin/bash ./init.sh

          mv ../../private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}/bdns.json ../../private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}/environment.js . 2>/dev/null

      - name: terraform apply
        run: |          
          cd ./LWA/terraform

          terraform apply --auto-approve

          mv bdns.json environment.js ../../private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}/
      
      - name: terraform state pull
        run: |          
          cd ./LWA/terraform

          terraform state pull > ../../private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}/terraform.tfstate

      - name: upload env
        run: |
          aws s3 cp --quiet ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env s3://tf-state-${AWS_REGION}-${AWS_ACCOUNT_ID}/${TF_VAR_network}/LWA/${TF_VAR_fqdn}/env

      - name: git commit & push
        run: |
          git add ./private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}
          git commit -m "Managed by Terraform - ./private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}"
          git pull && git push 
