name: deploy

on:
  workflow_call:
    inputs:
      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true

env:
  GIT_USERNAME: "terraform"
  GIT_EMAIL:    "terraform@pharmaledger.org"
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_BUILD_IAM_ROLE_TO_ASSUME_ARN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.gh_token }}
          repository: ${{ env.TF_VAR_gh_repo_name }}
          ref:        ${{ env.TF_VAR_gh_repo_ref }}
          path:       "./LWA"

      - name: download build
        run: |
          aws s3 cp s3://${{ env.AWS_BUILD_S3_BUCKET_NAME }}/${{ env.TF_VAR_app_build_version }}/lwa-build-${{ env.TF_VAR_app_build_version }}.zip lwa-build-${{ env.TF_VAR_app_build_version }}.zip

      - name: unzip build
        run: |
          ls -la

          mkdir ./LWA/terraform/build

          unzip lwa-build-${{ env.TF_VAR_app_build_version }}.zip -d ./LWA/terraform/build

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          
      - name: install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: |
          cd ./LWA/terraform

          /bin/bash ./init.sh

      - name: terraform apply
        run: |          
          cd ./LWA/terraform

          terraform apply --auto-approve
