name: build

on:
  workflow_call:
    inputs:
      aws_role_to_assume_arn:
        required: true
        type: string

      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true

env:
  GIT_USERNAME: "terraform"
  GIT_EMAIL:    "terraform@pharmaledger.org"
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.gh_token }}
          repository: ${{ env.GH_REPO_NAME }}
          ref:        ${{ env.GH_REPO_REF }}
          path:       "./LWA"

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME_ARN }}
          
      - name: install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: |
          cd ./LWA/terraform

          /bin/bash ./init.sh

      - name: terraform apply
        run: |
          cd ./LWA/terraform

          terraform plan
