name: build

on:
  workflow_call:
    inputs:
      aws_role_to_assume_arn:
        required: true
        type: string

      network_name:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
      
      gh_repo_ref:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true

env:
  TERRAFORM_VERSION: "1.8.3"

  GIT_USERNAME: "terraform"
  GIT_EMAIL:    "terraform@pharmaledger.org"

  GH_TOKEN:     ${{ secrets.gh_token }}
  GH_REPO_NAME: "pharmaledgerassoc/LWA"
  GH_REPO_REF:  ${{ inputs.gh_repo_ref }}

  AWS_IAM_ROLE_ARN_TO_ASSUME: ${{ inputs.aws_role_to_assume_arn }}

  NETWORK_NAME: ${{ inputs.network_name }}
  FQDN:         ${{ inputs.fqdn }}

  PREVENT_GITHUB_ORGANIZATION: ${{ inputs.prevent_github_organization }}
  GITHUB_ORGANIZATION:         ${{ inputs.github_organization }}
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
