name: destroy

on:
  workflow_call:
    inputs:
      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

           echo "TF_VAR_network=${{ inputs.network }}" >> $GITHUB_ENV
           echo "TF_VAR_fqdn=${{ inputs.fqdn }}" >> $GITHUB_ENV

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ inputs.aws_iam_role_to_assume_arn }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.gh_token }}
          repository: ${{ env.TF_VAR_gh_repo_name }}
          ref:        ${{ env.TF_VAR_gh_repo_ref }}
          path:       "./LWA"
          
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        run: |
          cd ./LWA/terraform

          /bin/bash ./init.sh

      - name: terraform destroy
        run: |          
          cd ./LWA/terraform

          terraform destroy --auto-approve
      
      - name: remove configuration
        run: |
          rm -rf ./private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}

      - name: git commit & push
        run: |
          git config --global user.email "terraform@pharmaledger.org"
          git config --global user.name "terraform"

          git add ./private/${{ inputs.network }}/LWA
          git commit -m "Managed by Terraform - ./private/${{ inputs.network }}/LWA/${{ inputs.fqdn }}"
          git pull && git push 
