name: git

on:
  workflow_call:
    inputs:
      network:
        required: true
        type:     string
      fqdn:
        required: true
        type:     string
    
    secrets:
      gh_token:
        required: true
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  commit_and_push:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: env
        run: |
           for var in $(cat ./private/${{ inputs.network }}/LWA/${{inputs.fqdn}}/env); do echo "${var}" >> $GITHUB_ENV ; done

           echo "TF_VAR_network=${{ inputs.network }}" >> $GITHUB_ENV
           echo "TF_VAR_fqdn=${{ inputs.fqdn }}" >> $GITHUB_ENV

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_BUILD_IAM_ROLE_TO_ASSUME_ARN }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token:      ${{ secrets.gh_token }}
          repository: ${{ env.TF_VAR_gh_repo_name }}
          ref:        ${{ env.TF_VAR_gh_repo_ref }}
          path:       "./LWA"

      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region:     ${{ env.TF_VAR_aws_region }}
          role-to-assume: ${{ env.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: terraform init
        run: |
          cd ./LWA/terraform

          /bin/bash ./init.sh

      - name: terraform state pull
        run: |          
          cd ./LWA/terraform

          terraform state pull > ./private/${{ inputs.network }}/${{ inputs.fqdn }}/terraform.tfstate
      
      - name: git commit & push
        run: |
          git add ./private/${{ inputs.network }}/${{ inputs.fqdn }}/terraform.tfstate
          git commit -m "Managed by Terraform - ./private/${{ inputs.network }}/${{ inputs.fqdn }}/terraform.tfstate"
          git pull && git push 
